services:
  db:
    image: postgres:15-alpine
    container_name: jota_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: jota
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jota"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api-server:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: jota_db_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/jota
    restart: unless-stopped

# Definición de volúmenes nombrados
volumes:
  postgres_data: